# Generated by Django 2.2.16 on 2022-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
